Pioneer/Models/ErrorViewModel.cs
namespace Pioneer.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pioneer/Models/Freshman.cs
using System.ComponentModel.DataAnnotations;

namespace Pioneer.Models
{
    public class Freshman
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter your registration number")]
        public string RegistrationNumber { get; set; }
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter your password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please re-enter your password")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Please enter your age")]
        public int Age { get; set; }
        [Required(ErrorMessage = "Please enter your mobile number")]
        public long MobileNumber { get; set; }
    }
}

Pioneer/Models/PioneerDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace Pioneer.Models
{
    public class PioneerDBContext : DbContext
    {
        public PioneerDBContext(DbContextOptions<PioneerDBContext> options) : base(options)
        {

        }

        // Implement code here
        public DbSet<Freshman> Freshmen { set; get; }
    }
}

Pioneer/Models/PioneerLogin.cs
using System.ComponentModel.DataAnnotations;

namespace Pioneer.Models
{
    public class PioneerLogin
    {
        [Required(ErrorMessage = "Please enter your registration number")]
        public string RegistrationNumber { get; set; }

        [Required(ErrorMessage = "Please enter your password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Pioneer/Controllers/PioneerController.cs
using Microsoft.AspNetCore.Mvc;
using Pioneer.Models;

namespace Pioneer.Controllers
{
    public class PioneerController : Controller
    {
        PioneerDBContext dbContext;
        public PioneerController(PioneerDBContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult PioneerPortal()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PioneerPortal(PioneerLogin login)
        {
            if (ModelState.IsValid)
            {
                var r = dbContext.Freshmen.Where
                        (l => l.RegistrationNumber == login.RegistrationNumber).FirstOrDefault();

                if (r != null)
                    return RedirectToAction("Dashboard", login);

                return View();
            }
            return View();
        }

        public IActionResult InsertFreshman()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult InsertFreshman(Freshman freshman)
        {
            if (ModelState.IsValid)
            {
                if (freshman.RegistrationNumber == freshman.Password)
                {
                    ViewBag.Message = "RegistrationNumber and Password should not be the same";
                }
                else
                {
                    dbContext.Freshmen.Add(freshman);
                    dbContext.SaveChanges();
                    return RedirectToAction("PioneerPortal");
                }

                return View();
            }

            return View();
        }

        public IActionResult Dashboard(PioneerLogin model)
        {
            return View(model);
        }
    }
}

Pioneer/Views/Pioneer/Dashboard.cshtml
@model Pioneer.Models.PioneerLogin

@{
    ViewData["Title"] = "Dashboard";
}

@{
    <h1 id="message">Your register number - @Model.RegistrationNumber is successfully inserted to PIONEER UNIVERSITY</h1>
}

<div>
    <a asp-controller="Pioneer"  asp-action="PionerPortal">Back to Login page</a>
</div>

Pioneer/Views/Pioneer/InsertFreshman.cshtml
@model Pioneer.Models.Freshman

@{
    ViewData["Title"] = "InsertFreshman";
}

<h1>InsertFreshman</h1>

<hr />
@{
    <h2>@ViewBag.Message</h2>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="InsertFreshman">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobileNumber" class="control-label"></label>
                <input asp-for="MobileNumber" class="form-control" />
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" id="btnAdd" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pioneer/Views/Pioneer/PioneerPortal.cshtml
@model Pioneer.Models.PioneerLogin

@{
    ViewData["Title"] = "PioneerPortal";
}

<h1>PioneerPortal</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PioneerPortal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" id="btnLogin" value="Login" class="btn btn-primary" />
                <a id="lnkRegister" asp-controller="Pioneer" asp-action="InsertFreshman">Register</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pioneer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pioneer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pioneer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pioneer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pioneer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>